const companies = [
  {
    name: 'Google',
    owner: 'Publicly Traded',
    phone: '123-456-7890',
    city: 'Mountain View',
    state: 'CA',
    deals: [],
    createdAt: new Date('December 17, 2005 03:24:00'),
    industry: 'Technology',
  },
  {
    name: 'Home Depot',
    owner: 'Bernard Marcus',
    phone: '432-555-6739',
    city: 'Atlanta',
    state: 'GA',
    deals: [],
    createdAt: new Date('January 27, 2001 05:55:00'),
    industry: 'Home Improvement',
  },
  {
    name: 'Sweetwater',
    owner: 'Chuck Surack',
    phone: '800-222-4700',
    city: 'Fort Wayne',
    state: 'IN',
    deals: [],
    createdAt: new Date('March 17, 2012 14:55:00'),
    industry: 'Music Supply',
  },
  {
    name: 'Harris Teeter',
    owner: 'Publicly Traded',
    phone: '800-432-6111',
    city: 'Matthews',
    state: 'NC',
    deals: [],
    createdAt: new Date('July 4, 2017 16:55:00'),
    industry: 'Grocery',
  },
  {
    name: 'Luxottica',
    owner: 'Leonardo Del Vecchio',
    phone: '674-209-2034',
    city: 'Milan',
    state: 'Italy',
    deals: [],
    createdAt: new Date('June 21, 2006 18:00:00'),
    industry: 'Apparel',
  },
  {
    name: 'Honda',
    owner: 'Publicly Traded',
    phone: '800-999-1009',
    city: 'Hamamatsu',
    state: 'Japan',
    deals: [],
    createdAt: new Date('August 12, 2016 12:00:00'),
    industry: 'Automotive',
  },
  {
    name: 'Alpaca Chicken',
    owner: 'Nora Palma',
    phone: '919-908-1597',
    city: 'Durham',
    state: 'NC',
    deals: [],
    createdAt: new Date('August 1, 2013 4:00:00'),
    industry: 'Restaraunts',
  },
  {
    name: 'British Petroleum',
    owner: 'Publicly Traded',
    phone: '784-986-5912',
    city: 'Houston',
    state: 'TX',
    deals: [],
    createdAt: new Date('November 8, 2017 14:00:00'),
    industry: 'Petrochemicals',
  },
  {
    name: 'Gibson Guitars',
    owner: 'James Curleigh',
    phone: '223-567-4039',
    city: 'Nashville',
    state: 'TN',
    deals: [],
    createdAt: new Date('December 5, 2015 19:00:00'),
    industry: 'Music Supply',
  },
  {
    name: 'ScubaPro',
    owner: 'Gustav Dalla Valle',
    phone: '875-966-2103',
    city: 'Racine',
    state: 'WI',
    deals: [],
    createdAt: new Date('April 3, 2013 22:00:00'),
    industry: 'Recreational Products',
  },
];

module.exports = companies;
